### PR TITLE
Update to latest ROS2 Humble & Navigation 2 

### PR DESCRIPTION
**Pull request by nakai-omer**

### CODE REVIEW

**Comment by mdrwiega** [comment]
Thank you for your changes!

**Comment by mdrwiega** [comment]
Looks like it failed on tests.

**Comment by nakai-omer** [comment]
@mdrwiega It failed on a test that validated the package.xml file, but probably due to different ros versions it failed, i have updated main.yaml to have the correct ros version

**Comment by nakai-omer** [comment]
@mdrwiega Hi, could you give me some hints on how to solve the CI failures, seems like it is running on Focal even though the setting is ubuntu-latest, this could cause Humble to not be found.

**Comment by mdrwiega** [comment]
Hi @nakai-omer. Maybe we should consider a change to `ubuntu-22.04` instead of `ubuntu-latest`, but I'm not sure.

**Comment by nakai-omer** [comment]
@mdrwiega Thanks for the hint, seems like you are right that ubuntu-latest, is actually ubuntu 20.04, I have updated the workflow to ubuntu 22.04, can you please re-run it?

**Comment by mdrwiega** [comment]
Another reason tests fail at this stage is a version of `ros-tooling/setup-ros`. I have updated it on the master to v0.3. The tests have passed there. Please try to rebase this branch to `master`.

**Pull request merged**
